version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: svalbard_postgres
    environment:
      POSTGRES_DB: svalbard_vaultdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d

  neo4j:
    image: neo4j:latest
    container_name: svalbard_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/svalbardpassword

  mongodb:
    image: mongo:latest
    container_name: svalbard_mongo
    ports:
      - "27017:27017"
